### ISSUE TITLE
Coquilles alpha 10.1

### ISSUE THREAD

**Issue by audreyazura** [ykonoclast/UPsysbase#61]
Chapitre V
- [x] exemple du remplissage de la jauge de force d'âme (p. 31): "Si elle perd une deuxième commotion" -> c'est probablement parce que je suis un peu fatiguée, mais "perdre une commotion" m'as un peu rendu confuse. "Si elle récupère d'une deuxième commotion" me semblerait mieux.

**Comment by audreyazura** [comment]
Chapitre IV
- [x] Combat à Mains nues : le combat à mains nues infligent-il des points de dégâts physiques ou chocs ?

**Comment by audreyazura** [comment]
Chapitre VII (désolée du mur de texte)
- [x] exemple de la progression (p. 46) : je ne suis pas sûre qu'utiliser la branche "Spécifique" pour l'exemple de capa que Caneus ne peut acheter est une bonne idée comme Cnaeus va gagner la capa 2 automatiquement. J'ai peur que le fait de dire "il ne peut pas encore l'acheter" induise le lecteur en erreur. Ce serait probablement mieux de faire tout l'exemple avec la branche "Finesse".
- [x] Compétence d'Élite, Coup de pommeau (p. 47) : si je comprend bien, il faut que tu infliges les dégâts, que la personne rate son jet d'absorption et alors tu infliges en plus tes dégâts à main nue et fait passer sa défense à 5 ?
`Oui, c'est dit quasiment exactement comme ça, je ne vais pas changer la formulation.`
- [x] Compétence d'Élite, Coup puissant (p. 47) : "en attaquant avec cette compétence et en obtenant un nombre d'incréments [...], si le coup passe la défense" -> il est possible d'obtenir des incréments sur un jet d'attaque sans passer la défense ?
`formulation modifiée.`
- [x] Compétence d'Élite, Double parade (p. 47) : faut-il parer avec cette conséquence ou avec la compétence de parade normale ?
`Double-parade, formulation modifiée.`
- [x] Compétence d'Élite, Feinte (p. 47) : il manque une majuscule à Mental.
- [x] Compétence d'Élite, Frappe brutale (p. 47) : il manque une majuscule à Physique.
- [x] Archerie, Branche Impact, Capa2 (p. 48) : il manque une majuscule à Coordination.
- [x] Archerie, Branche Portée, Capa3 (p. 48) : que sont les modificateurs spéciaux ?
`Ceux qui ne sont pas normaux pardi! Précision ajoutée.`
- [x] Archerie, Branche Spécifique, Capa2 (p. 48) : cette capa est en fait _moins_ intéressante que la capa1 de la branche Portée.
`Capa branche portée modifiée.`
- [x] Arme à distance, Branche Rapidité, Capa3 (p. 48) : c'est la même que la capa2 d'Archerie, branche rapidité.
`capa2 et 3 archerie switchée, en fait c'est mieux comme ça.`
- [x] Arme à distance, Branche Astuce, Capa1 (p. 49) : les attaques au càc avec une arme à feu se font bien avec attaque(catégorie d'arme) du domaine càc ?
`Non, armes improvisées maintenant, c'était pourri avant.`
- [x] Asssassinat, liste des compétences (p. 50) : il manque un espace avant "feinte" et une majuscule à ce F.
- [x] Asssassinat, Branche Mortalité, Capa1 (p. 50) : "le personnage gagne un incrément de plus plus"
- [x] Asssassinat, Branche Mortalité, Capa2 (p. 50) : si je comprend bien, à partir de ce moment, les incréments ajoutent au dégâts `floor([#incrément] * 1.5) * 3` ?
`Ha oui mais le gars doit être surpris! Genre, comme moi quand on me balance un floor dans la gueule pour une capa.`
- [x] Asssassinat, Branche Discrétion, Capa2 (p. 50) : il manque une majuscule à Présence. Aussi, je ne suis pas sûre de la logique d'utiliser la Présence ici.
`C'est vrai que c'est merdique, je mets furtivité, le MJ décide si ce sera avec présence ou coordination selon la situation.`
- [x] Asssassinat, Branche Discrétion, Capa3 (p. 50) : il manque une majuscule à Présence.
`Ben maintenant ce sera Furtivité, elle avait qu'à pas oublier sa majsucule la coquine.`
- [x] Deux armes, Branche Technique à deux mains, Capa3 (p. 51) : attaquer sur une interruption en ne dépensant que 2 actions ? Si oui, ça colle avec Archerie (où attaquer sur une interruption coûte 3 actions en capa2) mais est plus puissant que la capa3 dans Arme à distance, branche rapidité. Sinon, on se retrouve avec le même problème qu'avec Arme à distance, branche rapidité capa3 (être moins bien qu'une capa2).
`Je mets trois actions.`
- [x] Escrime, Branche Panache, Capa3 (p. 51) : il manque une majuscule à Présence. Aussi, c'est basiquement la compétence Suppression, mais moins intéressante ?
`Et moins chère, et donne une comp de plus à l'entraînement, et fonctionne avec des caracs déjà montées. Mais à part ça oui.`
- [x] Mains nues, Branche Arts Puissance (p. 52) : je pense qu'il y a une erreur dans le nom de cette branche.
- [x] Mains nues, Branche Arts Puissance, Capa2 (p. 52) : l'avantage « poing de fer » n'existe pas (plus ?). Je suppose qu'il s'agit de « poing de pierre ».
- [x] Mains nues, Branche Arts Puissance, Capa3 (p. 52) : blessure ou commotion ? (cf au-dessus)
- [x] Mains nues, Branche Contrôle, Capa2/3 (p. 52) : dans ce cas, les blessures ne sont pas infligées, c'est bien ça ? Et dans l'interaction avec la capa3, quand on atteint ce rang, chaque blessure converti augmente le prochain dé d'action ET réduit la force d'âme ? Ou c'est un OU ?
 `"en plus de sa deuxième capacité" ça me semble clair, je garde tel quel, c'est bien un ET.`
- [x] Mains nues, Branche Esquive, Capa3 (p. 52) : pas de dépense de force d'âme pour un truc aussi fort ?
 `"le mec est à mains nues, prend un peu pitié de lui.`

**Comment by audreyazura** [comment]
Chapitre VIII
- [x] Génération de PNJ (p. 55) : comment un ennemi RM5 peut avoir 3 points de force d'âme. Si je compte correctement, ses stats devraient 6, 5, 4, 3, 2, avec donc 2 points de force d'âme.
`Après tant d'années ce tableau continue de tricher. Il a été puni vertement.`
- [x] Veillissement (p. 56) : mais que se passe-t-il donc si l'on fait un jet entre 11 et 40 sur la table de vieillissement ? Le Grand Poulpe Cosmique nous dévore ?
`Et ce ne serait que justice pour cette insolence.`

**Comment by ykonoclast** [comment]
exemple de la progression (p. 46) : je ne comprends pas. Cnaeus a la capa1 de spécifique, il ne peut pas acheter la capa2 car il a pas le bon rang. Il peut encore moins acheter celle de finesse (car il a même pas la capa1) et, une fois la capa1 de finesse achetée, il ne gagnera pas automatiquement l'une plus que l'autre en passant rang 2 : il pourra choisir.

**Comment by audreyazura** [comment]
Ah, c'est aussi moi qui m'emmêlé les pinceaux : il me semblait que tu ne gagnais automatiquement que les capa de la branche dans laquelle tu avais débuté. Du coup ouais, ignore la remarque.

**Comment by audreyazura** [comment]
Chapitre IX (je m'arrête là pour aujourd'hui)
- [x] Armures et protections (p. 58) : que se passe-t-il pour si on 5,5 / 10,5 / etc... points d'armure ? On arrondit au supérieur ou à l'inférieur ?
`L'homme de goût ignore ce que signifie "arrondir à l'inférieur" et il rit des médiocres qui osent l'envisager. Comme on peut faire l'hypothèse que les lecteurs ignorent la règle du plus proche pair, il faut simplement arrondir arithmétiquement, comme ça s'apprend au collège. 
À noter : Fading'S UP emploie l'expression "arrondir à l'inférieur" dans un paragraphe, l'important pour un auteur est de ne pas se laisser intimider par la contradiction.`
- [x] Exemple des effets d'armures (p. 58) : je ne suis pas sûre que ça fasse sens de donner l'exemple de la flèche sur le bras de Cnaeus ici, comme il s'agit d'un coup visé.
`Vu que l'exemple en question porte sur les effets d'un coup ciblé je crains de devoir manifester mon désaccord.`
- [x] Armes (p. 60) : tant qu'on y est à faire des répétitions maintenant que pas mal de choses sont gravées dans le marbre, je pense que ce serait pas mal d'avoir un rappel des multiplicateurs d'incrément indicatifs ici.
`Non parce qu'ils ne sont pas censés être assignés aux armes de façon définitive. Le multiplicateur d'incréments ne concerne que les dégâts finaux et est interprété par le MJ. Oui, généralement une rapière fera du perçant mais... tu as entendu parler du coup de Jarnac?.`
- [x] Armes (p. 60) : je me dis que ce serait pas mal que dans la liste des caractéristiques des armes, tu montres que Physique Minimum est abbrévié avec la lettre phi dans les tableaux.
`Clairement il y a un risque que ce soit confondu avec une adhésion aux idéaux de la France Insoumise.`
- [x] Qualité et équilibrage des arnes (p. 60) : armes et non arnes
- [x] Armes improvisées (p. 61) : "La brute eﬀectue un jet d'Ataque(armes contondantes)" -> Attaque et non Ataque

**Comment by audreyazura** [comment]
> Exemple des effets d'armures (p. 58) : je ne suis pas sûre que ça fasse sens de donner l'exemple de la flèche sur le bras de Cnaeus ici, comme il s'agit d'un coup visé.
> `Vu que l'exemple en question porte sur les effets d'un coup ciblé je crains de devoir manifester mon désaccord.`

La règle des coups ciblés est pourtant donnée juste en-dessous de cet exemple.
`Quelle mauvaise foi, tu me déçois tellement. Clairement il fallait comprendre "coups ciblés sur une armure mais seulement quand il y a pas d'armure là..... bon ok je corrige`

**Comment by ykonoclast** [comment]
Cela fait beaucoup de modifications dans les entraînements. J'espère que nous n'avons rien cassé... l'équilibrage avait été délicat. Il n'est pas impossible que la dernière passe d'équilibrage ait aggravé certaines situations. Parfois l'équilibrage se faisait au niveau de la branche (une capa pourrie au rang 2 pour compenser une awesome au rang 3). J'ai bien l'impression que l'essentiel de ce que tu pointes est juste et que la réponse que j'y ai apporté contribue à mieux équilibrer les entraînements mais... encore une fois j'espère ne rien avoir cassé.

**Comment by audreyazura** [comment]
C'est vrai... Ça vaut peut-être le coup de demander à Eddy et Adrien d'y jeter un coup d'oeil plus précis. C'est nos spécialiste pour ça, après tout.

**Comment by ykonoclast** [comment]
10.2 sortie, merci.
