### ISSUE TITLE
Coquilles Alpha 13.1

### ISSUE THREAD

**Issue by XPoulpette** [ykonoclast/UPsysbase#65]
- [x] **p38 : Création et évolution + §2 :** ajouter un espace avant la parenthèse
- [x] **p39 : Spécialisations :** essayer de mettre "désiré" sur la 1ère colonne
- [x] **p39 : Agile :** espace en trop il me semble
- [x] **p39 : Loyauté 6XP :** espace en trop il me semble
- [x] **p40 : Appartenance 10XP :** manque un point
- [x] **p42 : Virulence :** manque un espace avant les 2 points
- [x] **p42 : Conduit ouvert :** "votres" mettre l'accent
- [x] **p43 : Perte de contrôle + Fascination :** mettre un tiret à "peut être" et "êtes vous" (2 fois) et "avez vous"
- [x] **p43 : Peu réactif :** "cous" à remplacer par "vous"
- [x] **p43 : Traumatisme :** mettre un tiret à "peut être" 
- [x] **p44 : Linguistique :** espaces en trop?
- [x] **p46 : Branches + Exemples :** Ajouter une virgule apres "spécifique"
- [x] **p47 : Frappe brutale :** essayer de mettre les quelques mots en haut de la colonne de droites en bas à gauche
- [x] **p47 : Double attaque :** espaces trop grands
- [x] **p48 : Archerie + Branche impact + Capa3 :** ajouter une virgule après "Dans ce cas"
- [x] **p48 : Archerie + Branche Célérité + Capa1 :** espaces trop grands
- [x] **p48 : Armes à distance + Comp élite :** espaces trop grands
- [x] **p50 : 2 armes + comp élite :** espaces trop grands
- [x] **p52 :** ajouter une image car ça fait un peu vide...

**Comment by ykonoclast** [comment]
- [x] 5 rangs pour les censives sur la feuille de fief, pas juste 3
