### ISSUE TITLE
Coquilles alpha 18

### ISSUE THREAD

**Issue by audreyazura** [ykonoclast/UPsysbase#68]
Chapitre XV :
- [x] p. 113, Arme de corps à corps futuriste : Est-ce que l'arme neural est vraiment NT3 ? Ce que tu décris rappel pas mal un taser, ce qu'on a, en fait.
`Et.... pas tout à fait. Le taser est une arme dédiée à cela et qui nécessite du temps (pas immédiat) et n'est pas une arme de corps à corps vraiment. Aucun couteau ou épée ne possède un espèce de taser intégré à fonctionnement immédiat. La règle décrite ici décrit ça ou alors carrément une dague avec une lame d'énergie faisant ce type de dégât (là encore immédiatement, sans insister plusieurs secondes).`
- [x] p. 114, Arme à feu futuriste, munition spéciale : les munitions expansives augmente la VD de 5, celles explosives augmentent les dégâts de 5. N'est-ce pas la même chose dans le système actuel ?
`Elle est vieille en plus cette erreur....`
- [x] p. 114, Arme lourde de tir futuriste, NT+2 : passer en P de physique en majuscule.
- [x] p. 115, table des effets de réglage : le "E" de "Réglage" est renvoyé à la ligne
`Pas chez moi`
- [x] p. 116, Pour aller plus loin : "On peut aussi décider de faire des versions automatiques de certaines des armes suivantes" -> ce n'est pas de ta faute, mais vu que la description des armes et les tableaux sont à la page précédente, utiliser "les armes suivantes" fait  vraiment bizarre. Peut-être une expression plus neutre en terme de positionnement (par ex., "les armes présentées ici") serait mieux.
`Je ne vois pas trop de qui ça pourrait être la faute à part moi vu que c'est moi qui ai positionné le tableau à un autre endroit que là où il était auparavant,`
- [x] p. 116, Modulateur de champs : "un modulateur de champ permet de neutraliser un champ de force du même niveau technologique" -> mais pas ceux d'un niveau inférieur ? (je chipotes, mais je suis là pour ça)
- [x] p. 116, Traducteur automatique : la mise sous forme de liste s'arrête après le NT 4.
- [x] p. 116, Combinaison d'isolation : "elle oﬀre un nombre de bonus de 5 égal à son niveau technologique – 1 à tout jet pour échapper à la détection" -> je me sens moins seule à faire des tournures de phrases très tordues. Je propose "elle offre un bonus de 5 × (NT – 1) à tout jet pour échapper à la détection".
- [x] p. 117, Scanner portable : un problème de mise en forme (interparagraphe trop large) et même problème que ci-dessus avec le "nombre de bonus de 5 égal à...".
`Les deux tournures ci-dessus proviennent de la suppression des augmentations gratuites il y a dix ans, cela a donné lieu des rechercher/remplacer par "bonus de 5" parfois un peu sauvages.`
- [x] p. 117, Cuve de soin : je pense qu'il faut une réécriture de la chose. J'ai une idée de ce que ça fait mais ça reste vraiment pas clair pour moi. Le double "tout en faisant" n'aide pas.
`J'enlève le double "de plus" mais le reste est correct. Le problème n'est pas la cuve de soin mais le fait que les règles de guérison sont complexes (stabilisation, guérison auto, jets médicaux de guérison sup, temps pour cela etc.). Mais les règles de matos n'ont pas vocation à ré-expliquer les règles de base, le lecteur n'à qu'à se référer au chapitre 5 si il ne se rappelle pas de tout (même moi je le fais car effectivement ce n'est pas des plus simples).`
- [x] p. 118, Hypospray, Anetrizine : "Une erreur de dosage cause des dégâts (-1 en mental)." -> ok, mais comment tu fais une erreur de dosage ?
`Et dieu inventa le MJ...`
- [x] p. 118, Hypospray, Cateline : p majuscule à physique.
- [x] p. 118, Hypospray, Kayolane : v majuscule à volonté.
- [x] p. 119, Hypospray, Lexorine : m majuscule à mental.
- [x] p. 119, Hypospray, Melorazine : v majuscule à volonté.
- [x] p. 119, Outil réplicateur : c'est le seul matériel pour lequel tu mets un "+" après le NT.
`il a été rajouté après, je crois qu'il vient de Polaris alors que le reste venait de Star Trek`

**Comment by ykonoclast** [comment]
Ok, j'ai pris en compte presque tout. Bémols sur les armes neurales, les cuves de soin et l'anetrizine.

**Comment by audreyazura** [comment]
**Armes neurales :** Ok, je vois la différence, pas de soucis du coup.

**Cuve de soin :** Je pense que si tu pouvais séparer en deux phrases ou plus, ça aiderait aussi. Ce serait un peu plus digeste.
`Effectivement`
**Anetrizine :** Eh, vu que ça a un effet explicite, j'aurais bien vu une petite indication pour aider le MJ à décider, justement. C'est quelque chose qui peut arriver en dehors du scénar et donc sur lequel il est bon de pouvoir se protéger un peu de l'arbitraire ?
`On est dans les règles très optionnelles génériques. Elles sont moins précises car presque forcément toujours à adapter.`
