### ISSUE TITLE
Pour version finale

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/UPsysbase#69]
- [ ] Tester jaunes alternatifs : actuel peut mal passer à l'impression (tester sans conversion couleur spot au préalable)
- [ ] Ombre portée sous cadres annexes
- [ ] dénerfer l'épée courte

**Comment by audreyazura** [comment]
- [ ] p. 33, Stabilisation médicale: il serait bon de préciser que le jet doit être fait pour chaque blessure.
