### ISSUE TITLE
Correction de la RC1

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/UPsysbase#72]
- [x] Dans le sommaire, la partie introductive a encore un décalage de deux pages.
- [x] p.59 : générateur de roleplay encore genré, y mettre la table à jour (celle des annexes) à la place.
- [ ] Voir pour quand même assombrir le jaune : sort mal en l´état sur certaines imprimantes.

**Comment by audreyazura** [comment]
- [x] p. 78, créer un effet: 5 écrit en toute lettre dans le calcul du ND
- [x] C'est peut-être moi, mais je ne retrouve plus où tu as défini l'aridité mentale
